# Generated by Django 3.2.25 on 2024-04-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
