# Generated by Django 4.2.10 on 2024-04-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ok', '0002_auto_20240411_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tin', models.CharField(max_length=100)),
                ('issuerid', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('accounts', models.TextField()),
            ],
        ),
    ]
